apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app-1
  namespace: default
  labels:
    app: my-nginx-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx-app-1
  template:
    metadata:
      labels:
        app: my-nginx-app-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        env:
        - name: ENVIRONMENT
          value: production
